image : mcr.microsoft.com/dotnet/core/sdk:latest

stages:
  - build
  - test

build:
  stage: build
  tags: 
  - shared-windows
  script:
    - dotnet build

test:
  stage: test
  tags: 
  - shared-windows
  script:
    - dotnet test