name: Running the tests

on: [push, pull_request]

jobs:
  running-tests:
    name: Running the tests
    runs-on: ubuntu-latest
    steps:
      - name: Getting code
        uses: actions/checkout@v2
      - name: Setup dotnet 5.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.202'
      - name: Install dependencies
        run: dotnet restore
      - name: Build the project
        run: dotnet build
      - name: Test the project
        run: dotnet test