name: Running the tests

on: [push, pull_request]

jobs:
  running-tests:
    name: Running the tests
    runs-on: windows-latest
    steps:
      - name: Getting code
        uses: actions/checkout@v2
      - name: Setup dotnet 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.0'
      - name: Install dependencies
        run: dotnet restore
      - name: Build the project
        run: dotnet build
      - name: Test the project
        run: dotnet test